namespace GWBASIC.Core.Common;

/// <summary>
/// Standard GW-BASIC error codes and messages.
/// </summary>
public enum BasicErrorCode
{
    None = 0,
    NextWithoutFor = 1,
    SyntaxError = 2,
    ReturnWithoutGosub = 3,
    OutOfData = 4,
    IllegalFunctionCall = 5,
    Overflow = 6,
    OutOfMemory = 7,
    UndefinedLineNumber = 8,
    SubscriptOutOfRange = 9,
    DuplicateDefinition = 10,
    DivisionByZero = 11,
    IllegalDirect = 12,
    TypeMismatch = 13,
    OutOfStringSpace = 14,
    StringTooLong = 15,
    StringFormulaTooComplex = 16,
    CannotContinue = 17,
    UndefinedUserFunction = 18,
    NoResume = 19,
    ResumeWithoutError = 20,
    UnprintableError = 21,
    MissingOperand = 22,
    LineBufferOverflow = 23,
    DeviceTimeout = 24,
    DeviceFault = 25,
    ForWithoutNext = 26,
    OutOfPaper = 27,
    WhileWithoutWend = 29,
    WendWithoutWhile = 30,
    FieldOverflow = 50,
    InternalError = 51,
    BadFileNumber = 52,
    FileNotFound = 53,
    BadFileMode = 54,
    FileAlreadyOpen = 55,
    DeviceIOError = 57,
    FileAlreadyExists = 58,
    DiskFull = 61,
    InputPastEnd = 62,
    BadRecordNumber = 63,
    BadFileName = 64,
    TooManyFiles = 67,
    DeviceUnavailable = 68,
    PermissionDenied = 70,
    DiskNotReady = 71,
    DiskMediaError = 72,
    AdvancedFeatureDisabled = 73,
    RenameAcrossDisks = 74,
    PathFileAccessError = 75,
    PathNotFound = 76
}

public static class BasicErrorMessages
{
    public static string GetMessage(BasicErrorCode code) => code switch
    {
        BasicErrorCode.NextWithoutFor => "NEXT without FOR",
        BasicErrorCode.SyntaxError => "Syntax error",
        BasicErrorCode.ReturnWithoutGosub => "RETURN without GOSUB",
        BasicErrorCode.OutOfData => "Out of DATA",
        BasicErrorCode.IllegalFunctionCall => "Illegal function call",
        BasicErrorCode.Overflow => "Overflow",
        BasicErrorCode.OutOfMemory => "Out of memory",
        BasicErrorCode.UndefinedLineNumber => "Undefined line number",
        BasicErrorCode.SubscriptOutOfRange => "Subscript out of range",
        BasicErrorCode.DuplicateDefinition => "Duplicate Definition",
        BasicErrorCode.DivisionByZero => "Division by zero",
        BasicErrorCode.IllegalDirect => "Illegal direct",
        BasicErrorCode.TypeMismatch => "Type mismatch",
        BasicErrorCode.OutOfStringSpace => "Out of string space",
        BasicErrorCode.StringTooLong => "String too long",
        BasicErrorCode.StringFormulaTooComplex => "String formula too complex",
        BasicErrorCode.CannotContinue => "Can't continue",
        BasicErrorCode.UndefinedUserFunction => "Undefined user function",
        BasicErrorCode.NoResume => "No RESUME",
        BasicErrorCode.ResumeWithoutError => "RESUME without error",
        BasicErrorCode.UnprintableError => "Unprintable error",
        BasicErrorCode.MissingOperand => "Missing operand",
        BasicErrorCode.LineBufferOverflow => "Line buffer overflow",
        BasicErrorCode.DeviceTimeout => "Device Timeout",
        BasicErrorCode.DeviceFault => "Device Fault",
        BasicErrorCode.ForWithoutNext => "FOR without NEXT",
        BasicErrorCode.OutOfPaper => "Out of Paper",
        BasicErrorCode.WhileWithoutWend => "WHILE without WEND",
        BasicErrorCode.WendWithoutWhile => "WEND without WHILE",
        BasicErrorCode.FieldOverflow => "FIELD overflow",
        BasicErrorCode.InternalError => "Internal error",
        BasicErrorCode.BadFileNumber => "Bad file number",
        BasicErrorCode.FileNotFound => "File not found",
        BasicErrorCode.BadFileMode => "Bad file mode",
        BasicErrorCode.FileAlreadyOpen => "File already open",
        BasicErrorCode.DeviceIOError => "Device I/O Error",
        BasicErrorCode.FileAlreadyExists => "File already exists",
        BasicErrorCode.DiskFull => "Disk full",
        BasicErrorCode.InputPastEnd => "Input past end",
        BasicErrorCode.BadRecordNumber => "Bad record number",
        BasicErrorCode.BadFileName => "Bad file name",
        BasicErrorCode.TooManyFiles => "Too many files",
        BasicErrorCode.DeviceUnavailable => "Device Unavailable",
        BasicErrorCode.PermissionDenied => "Permission Denied",
        BasicErrorCode.DiskNotReady => "Disk not Ready",
        BasicErrorCode.DiskMediaError => "Disk media error",
        BasicErrorCode.AdvancedFeatureDisabled => "Advanced Feature disabled",
        BasicErrorCode.RenameAcrossDisks => "Rename across disks",
        BasicErrorCode.PathFileAccessError => "Path/File access error",
        BasicErrorCode.PathNotFound => "Path not found",
        _ => $"Error {code}"
    };
}
